# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1cCuKXC9jwxTkcoC_g2q8F943G_iSIU

1. Write a function that finds the sum of the

a.) first n odd terms
"""

# Python Program to Calculate Sum of Odd Numbers from 1 to N
 
maximum = int(input(" Please Enter the number : "))
Oddtotal = 0

for number in range(1, maximum+1):
    if(number % 2 != 0):
        print("{0}".format(number))
        Oddtotal = Oddtotal + number

print("The Sum of Odd Numbers from 1 to {0} = {1}".format(number, Oddtotal))

"""b.) first n even terms"""

# Python program to Calculate Sum of even numbers
n=int(input("Enter the Number : "))
s=0
for i in range(0,n+1,2):
    s=s+i
print("The sum of even Numbers  : ",s)

"""c) 1, 2, 4, 3, 5, 7, 9, 6, 8, 10, 11, 13.. till n-th term"""

# Python Programe to calculate sun of 1, 2, 4, 3, 5, 7, 9, 6, 8, 10, 11, 13.. till n-th term
n=int(input("Enter the number of terms: "))
i=1
s=0
while(i<=n):
  s=s+i
  i=i+1
print("Sum is: ",s)

"""2. Consider a tuple t1=(1,2,5,7,9,2,4,6,8,10). Write a program to perform following operations:

a. Print half the values of tuple in one line and the other half in the next line.
"""

tpl = (1,2,5,7,9,2,4,6,8,10)

for i in range(0,5):
    print(tpl[i],end = ' ')
print()
for i in range(5,10):
    print(tpl[i],end = ' ')

"""b. Print another tuple whose values are even numbers in the given tuple. """

tpl = (1,2,5,7,9,2,4,6,8,10)
tpl1 = tuple(i for i in tpl if i%2 == 0)
print(tpl1)

"""c.) Concatenate a tuple t2=(11,13,15) witht1"""

# initialize tuples
test_tup1 = (1,2,5,7,9,2,4,6,8,10)
test_tup2 = (11,13,15)

# printing original tuples
print("The original tuple 1 : " + str(test_tup1))
print("The original tuple 2 : " + str(test_tup2))

# Ways to concatenate tuples
# using + operator
res = test_tup1 + test_tup2

# printing result
print("The tuple after concatenation is : " + str(res))

"""d. Return maximum and minimum value from this tuple"""

# initializing list
test_list = [(1, 2, 5, 7, 9, 2, 4, 6, 8, 10, 11, 13, 15)]

# printing original list
print ("The original list is : " + str(test_list))

res1 = min(test_list)[0] 
res2 = max(test_list)[12]

# printing result
print ("The min of index  : " + str(res1))
print ("The max of index  : " + str(res2))

"""3. Write a menu driven program to perform the following functions on strings:

a. Find the length of string
"""

str = input("Enter a string: ")
counter = 0
for s in str:
      counter = counter+1
print("Length of the input string is:", counter)

"""b.) Return maximum of three strings """

def maximum(a, b, c): 
   list = [a, b, c] 
   return max(list) 
# Driven code  
x = str(input("Enter First number"))
y = str(input("Enter Second number"))
z = str(input("Enter Third number"))
print("Maximum Number is ::>",maximum(x, y, z))

"""c. Accept a string and replace every successive character with ‘#’ Example- For Given string ‘Hello World’ returned string is ‘H#l#o W#r#d’."""

def changer():
    ch=[]
    for i in 'Hello World':
        ch.append(i)
    for j in range(1,len(ch),2):
        ch[j]= '#'
    s=''
    for k in ch:
        s=s + k
    print(s)
changer()

"""d. Find number of words in the given string


"""

string="Can you can a can as a canner can can a can?"
# if you want to take cases into account remove this line
string=string.lower()
# between index=8 and 17, how many times the word 'can' occurs
print(string.count("can",8,17)